load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["entropy.go"],
    importpath = "github.com/neticdk/jytte/pkg/entropy",
    visibility = ["//visibility:public"],
)
